# Site settings
title: This is actually working
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /probable-adventure # the subpath of your site, e.g. /blog/
url: https://skhan890.github.io # the base hostname & protocol for your site
github_username:  skhan890
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
