# Site settings
title: A probable (probably) adventure
description: > # this means to ignore newlines until "baseurl:"
  This is my for my culminating project 
  for the INFO 550 Software Engineering, Emory University, Rollins School of Public Health.
baseurl: /probable-adventure # the subpath of your site, e.g. /blog/
url: https://skhan890.github.io # the base hostname & protocol for your site
github_username:  skhan890
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
