---
layout: post
title:  sars!
date: `r Sys.time()`
published: true
tags: [example1, example2]
---

Your markdown here!

```{r,echo=F,eval=T,message=F,warning=F}
library(metricsgraphics)
library(rCharts)
library(RColorBrewer)
load("C:/Users/Sars/Documents/Spring 2016/Software Engineering/Project/probable-adventure/_source/sars/heroStats.RData")
```
<!-- blog_gen() -->

```{r}

heroStats %>%
  mjs_plot(x=Rank, y=damage) %>%
  mjs_point(color_accessor=HeroClass,
            x_rug=TRUE, y_rug=TRUE,
            # size_accessor=Rank,
            # size_range=c(5, 10),
            color_type="category",
            color_range=brewer.pal(n=7, name="Spectral")[c(1, 5, 7)]) %>%
  mjs_labs(x="Rank of player", y="Damage") %>% 
  mjs_add_legend(legend="Y")


```
n1$save('mychart2.html', standalone = TRUE)
```{r results = 'asis', comment = NA}
# require(rCharts)
# n1 <- nPlot(thorns ~ Rank, data = heroStats[1:100,], group='HeroClass', type = "scatterChart")
# n1$show('inline', include_assets = TRUE, cdn = TRUE)
```
<iframe src="C:/Users/Sars/Documents/Spring 2016/Software Engineering/Project/probable-adventure/figure/source/sars/2016-05-02-sars/mychart2.html"
        height="600" width="100%"
        scrolling="no" seamless="seamless"
        frameBorder="0">
</iframe>
          

babes23
getwd()
